version: "3.0"

services:
  dataset:
    build:
      context: .
    image: {{projectName}}
    restart: unless-stopped
    external_links:
      - redis:redis
      - mongo:mongo
      - nats:nats
    network_mode: bridge
